### ISSUE TITLE
categorical prior loss

### ISSUE THREAD

**Issue by patrickltobing** [RuiShu/vae-clustering#12]
Hi, thank you for the great solution.

Though, regarding the prior loss term,
I think the number of mixtures `K` should be included in `labeled_loss(x, px_logit, ...):`,
https://github.com/RuiShu/vae-clustering/blob/master/shared_subgraphs.py#L31,
so it will return `xy_loss + np.log(K)`.

**Comment by sghalebikesabi** [comment]
He correctly writes xy_loss - np.log(0.1) = xy_loss - np.log(1/K) = xy_loss + np.log(K)
